In [ ]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("drowsyng/medicines-dataset")

print("Path to dataset files:", path)

Using Colab cache for faster access to the 'medicines-dataset' dataset.
Path to dataset files: /kaggle/input/medicines-dataset

In [ ]:
import os

files = os.listdir(path)

print(files)

['medicines.csv']

**Read the file**

In [ ]:
import pandas as pd

csv_path = path + "/medicines.csv"

df = pd.read_csv(csv_path)

print(df.shape)

df.head()

(23939, 13)

,disease_name,disease_url,med_name,med_url,final_price,price,prescription_required,drug_varient,drug_manufacturer,drug_manufacturer_origin,drug_content,generic_name,img_urls
0,ADHD (7),https://www.netmeds.com/prescriptions/adhd,Atrest 25mg Tablet 10'S,https://www.netmeds.com/prescriptions/atrest-2...,₹335.68,MRP ₹381.46 Save 12 %,Rx required,*10 Tablet(s) in a Strip,* Mkt: Centaur Pharmaceuticals Pvt Ltd,* Country of Origin: India,INTRODUCTION ABOUT ATREST 25MG TABLETATREST 25...,Generic Name Tetrabenazine 25 mg,https://www.netmeds.com/images/product-v1/600x...
1,ADHD (7),https://www.netmeds.com/prescriptions/adhd,Capnea Injection 1ml,https://www.netmeds.com/prescriptions/capnea-i...,₹246.88,MRP ₹280.55 Save 12 %,Rx required,NaN,* Mkt: Cipla Ltd,* Country of Origin: India,INTRODUCTION ABOUT CAPNEA INJECTIONCAPNEA INJE...,Generic Name Caffeine 20 mg,https://www.netmeds.com/images/product-v1/600x...
2,ADHD (7),https://www.netmeds.com/prescriptions/adhd,Capnea Oral Solution 1ml,https://www.netmeds.com/prescriptions/capnea-s...,MRP ₹275.15,MRP ₹ 275.15,Rx required,NaN,* Mkt: Cipla Ltd,* Country of Origin: India,INTRODUCTION ABOUT CAPNEA SOLUTIONCAPNEA SOLUT...,Generic Name Caffeine 20 mg,https://www.netmeds.com/images/product-v1/600x...
3,ADHD (7),https://www.netmeds.com/prescriptions/adhd,Cognistar 30mg Injection 1'S,https://www.netmeds.com/prescriptions/cognista...,₹706.02,MRP ₹802.30 Save 12 %,Rx required,NaN,* Mkt: Lupin Ltd,* Country of Origin: India,INTRODUCTIONCOGNISTAR 30MG contains Cerebropro...,Generic Name Cerebroprotein Hydrolysate 30 mg,https://www.netmeds.com/images/product-v1/600x...
4,ADHD (7),https://www.netmeds.com/prescriptions/adhd,Cognistar 60mg Injection 1's,https://www.netmeds.com/prescriptions/cognista...,₹1314.90,MRP ₹1494.20 Save 12 %,Rx required,NaN,* Mkt: Lupin Ltd,* Country of Origin: India,INTRODUCTION ABOUT COGNISTAR 60MG INJECTIONCOG...,Generic Name Cerebroprotein Hydrolysate 60 mg,https://www.netmeds.com/images/product-v1/600x...

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23939 entries, 0 to 23938
Data columns (total 13 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   disease_name              23939 non-null  object
 1   disease_url               23939 non-null  object
 2   med_name                  23939 non-null  object
 3   med_url                   23939 non-null  object
 4   final_price               23939 non-null  object
 5   price                     23181 non-null  object
 6   prescription_required     21109 non-null  object
 7   drug_varient              15199 non-null  object
 8   drug_manufacturer         23760 non-null  object
 9   drug_manufacturer_origin  23760 non-null  object
 10  drug_content              23756 non-null  object
 11  generic_name              23569 non-null  object
 12  img_urls                  23760 non-null  object
dtypes: object(13)
memory usage: 2.4+ MB

In [ ]:
df.isnull().sum()

disease_name                   0
disease_url                    0
med_name                       0
med_url                        0
final_price                    0
price                        758
prescription_required       2830
drug_varient                8740
drug_manufacturer            179
drug_manufacturer_origin     179
drug_content                 183
generic_name                 370
img_urls                     179
dtype: int64

**Data Cleaning**

In [ ]:
import re

In [ ]:
df['disease_name'] = df['disease_name'].str.replace(r"\(\d+\)", "", regex=True)

df['disease_name'] = df['disease_name'].str.strip()

In [ ]:
df['drug_manufacturer'] = (
    df['drug_manufacturer']
    .str.replace("* Mkt:", "", regex=False)
    .str.strip()
)

In [ ]:
df['drug_manufacturer_origin'] = (
    df['drug_manufacturer_origin']
    .str.replace("* Country of Origin:", "", regex=False)
    .str.strip()
)

In [ ]:
df['generic_name'] = (
    df['generic_name']
    .str.replace("Generic Name","",regex=False)
    .str.strip()
)

In [ ]:
df[['disease_name',
    'drug_manufacturer',
    'drug_manufacturer_origin',
    'generic_name']].head(10)

,disease_name,drug_manufacturer,drug_manufacturer_origin,generic_name
0,ADHD,Centaur Pharmaceuticals Pvt Ltd,India,Tetrabenazine 25 mg
1,ADHD,Cipla Ltd,India,Caffeine 20 mg
2,ADHD,Cipla Ltd,India,Caffeine 20 mg
3,ADHD,Lupin Ltd,India,Cerebroprotein Hydrolysate 30 mg
4,ADHD,Lupin Ltd,India,Cerebroprotein Hydrolysate 60 mg
5,ADHD,Linux Laboratories Pvt Ltd,India,Cerebroprotein Hydrolysate 90 mg
6,Acne,Menarini India Pvt Ltd,India,Tretinoin 0.025 %
7,Acne,Menarini India Pvt Ltd,India,Tretinoin 0.05 %
8,Acne,Menarini India Pvt Ltd,India,Tretinoin 0.1 %
9,Acne,Lupin Ltd,India,Adapalene 0.1 %+Benzoyl Peroxide 2.5 %

**getting the number from final price **

In [ ]:
# استخراج الرقم من final_price

df['final_price_clean'] = (
    df['final_price']
    .str.extract(r'(\d+\.?\d*)')[0]
    .astype(float)
)

df[['final_price','final_price_clean']].head(10)

    final_price  final_price_clean
0       ₹335.68             335.68
1       ₹246.88             246.88
2  MRP  ₹275.15             275.15
3       ₹706.02             706.02
4      ₹1314.90            1314.90
5  MRP  ₹250.90             250.90
6  MRP  ₹126.00             126.00
7  MRP  ₹162.00             162.00
8  MRP  ₹205.00             205.00
9       ₹409.33             409.33

In [ ]:
# استخراج السعر الأصلي من price

df['price_clean'] = (
    df['price']
    .str.extract(r'(\d+\.?\d*)')[0]
)

df['price_clean'] = pd.to_numeric(
    df['price_clean'],
    errors='coerce'
)

df[['price','price_clean']].head(10)

                     price  price_clean
0   MRP ₹381.46  Save 12 %       381.46
1   MRP ₹280.55  Save 12 %       280.55
2             MRP ₹ 275.15       275.15
3   MRP ₹802.30  Save 12 %       802.30
4  MRP ₹1494.20  Save 12 %      1494.20
5             MRP ₹ 250.90       250.90
6             MRP ₹ 126.00       126.00
7             MRP ₹ 162.00       162.00
8             MRP ₹ 205.00       205.00
9   MRP ₹465.15  Save 12 %       465.15

In [ ]:
df[['final_price_clean','price_clean']].describe()

       final_price_clean    price_clean
count       23760.000000   23181.000000
mean          375.535661     366.187038
std          2301.183179    2512.318524
min             1.710000       1.000000
25%            87.120000      90.000000
50%           152.605000     158.510000
75%           275.000000     277.000000
max        136503.000000  151670.000000

In [ ]:
df['knowledge_text'] = (

    "Disease: " + df['disease_name'].fillna('') +

    " | Medicine: " + df['med_name'].fillna('') +

    " | Generic: " + df['generic_name'].fillna('') +

    " | Manufacturer: " + df['drug_manufacturer'].fillna('') +

    " | Prescription: " + df['prescription_required'].fillna('Unknown') +

    " | Price: " + df['final_price_clean'].astype(str) +

    " | Description: " + df['drug_content'].fillna('')

)

In [ ]:
df['knowledge_text'].head(2)

0    Disease: ADHD | Medicine: Atrest 25mg Tablet 1...
1    Disease: ADHD | Medicine: Capnea Injection 1ml...
Name: knowledge_text, dtype: object

**Checking for dublicate**

In [ ]:
print("Duplicated rows:", df.duplicated().sum())

print("Duplicated medicine names:",
      df['med_name'].duplicated().sum())

Duplicated rows: 0
Duplicated medicine names: 0

In [ ]:
duplicates = df[df['med_name'].duplicated(keep=False)]

duplicates[['disease_name','med_name']].head(20)

Empty DataFrame
Columns: [disease_name, med_name]
Index: []

**Checking for number of disease**

In [ ]:
print("Unique diseases:",df['disease_name'].nunique())

df['disease_name'].value_counts().head(20)

Unique diseases: 141

disease_name
Hypertension               1000
Fungal Infections          1000
High Cholesterol           1000
Diabetes                   1000
Bacterial Infections       1000
Pain relief                1000
Supplements                1000
Ulcer/Reflux/Flatulence    1000
Epilepsy/Convulsion         796
Skin Infections             739
Allergies                   718
Cough And Cold              696
Asthma/COPD                 679
Neuropathic Pain            637
Hormonal Therapy            593
Dry Skin                    584
Blood Clot                  569
Depression                  547
Cancer Oncology             404
Schizophrenia               403
Name: count, dtype: int64

In [ ]:
df[df['disease_name']=="Other"].shape

(0, 16)

In [ ]:
df[df['disease_name']=="Other"][
    ['med_name','generic_name']
].head(10)

Empty DataFrame
Columns: [med_name, generic_name]
Index: []

In [ ]:
final_df = df[[
    'disease_name',
    'med_name',
    'generic_name',
    'final_price_clean',
    'prescription_required',
    'drug_manufacturer',
    'drug_content',
    'knowledge_text'
]]

print(final_df.shape)

final_df.head()

(23939, 8)

,disease_name,med_name,generic_name,final_price_clean,prescription_required,drug_manufacturer,drug_content,knowledge_text
0,ADHD,Atrest 25mg Tablet 10'S,Tetrabenazine 25 mg,335.68,Rx required,Centaur Pharmaceuticals Pvt Ltd,INTRODUCTION ABOUT ATREST 25MG TABLETATREST 25...,Disease: ADHD | Medicine: Atrest 25mg Tablet 1...
1,ADHD,Capnea Injection 1ml,Caffeine 20 mg,246.88,Rx required,Cipla Ltd,INTRODUCTION ABOUT CAPNEA INJECTIONCAPNEA INJE...,Disease: ADHD | Medicine: Capnea Injection 1ml...
2,ADHD,Capnea Oral Solution 1ml,Caffeine 20 mg,275.15,Rx required,Cipla Ltd,INTRODUCTION ABOUT CAPNEA SOLUTIONCAPNEA SOLUT...,Disease: ADHD | Medicine: Capnea Oral Solution...
3,ADHD,Cognistar 30mg Injection 1'S,Cerebroprotein Hydrolysate 30 mg,706.02,Rx required,Lupin Ltd,INTRODUCTIONCOGNISTAR 30MG contains Cerebropro...,Disease: ADHD | Medicine: Cognistar 30mg Injec...
4,ADHD,Cognistar 60mg Injection 1's,Cerebroprotein Hydrolysate 60 mg,1314.90,Rx required,Lupin Ltd,INTRODUCTION ABOUT COGNISTAR 60MG INJECTIONCOG...,Disease: ADHD | Medicine: Cognistar 60mg Injec...

In [ ]:
final_df.isnull().sum()

disease_name                0
med_name                    0
generic_name              370
final_price_clean         179
prescription_required    2830
drug_manufacturer         179
drug_content              183
knowledge_text              0
dtype: int64

In [ ]:
# تعويض النصوص
final_df['generic_name'] = final_df['generic_name'].fillna('Unknown')

final_df['prescription_required'] = (
    final_df['prescription_required']
    .fillna('Unknown')
)

final_df['drug_manufacturer'] = (
    final_df['drug_manufacturer']
    .fillna('Unknown')
)

final_df['drug_content'] = (
    final_df['drug_content']
    .fillna('No description available')
)

# تعويض السعر بالـ median
median_price = final_df['final_price_clean'].median()

final_df['final_price_clean'] = (
    final_df['final_price_clean']
    .fillna(median_price)
)

/tmp/ipykernel_6679/4079910245.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_df['generic_name'] = final_df['generic_name'].fillna('Unknown')
/tmp/ipykernel_6679/4079910245.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_df['prescription_required'] = (
/tmp/ipykernel_6679/4079910245.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_df['drug_manufacturer'] = (
/tmp/ipykernel_6679/4079910245.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_df['drug_content'] = (
/tmp/ipykernel_6679/4079910245.py:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_df['final_price_clean'] = (

In [ ]:
final_df.isnull().sum()

disease_name             0
med_name                 0
generic_name             0
final_price_clean        0
prescription_required    0
drug_manufacturer        0
drug_content             0
knowledge_text           0
dtype: int64

**detecting noise **

In [ ]:
final_df.loc[:, 'drug_content'] = (
    final_df['drug_content']
    .str.replace(r'INTRODUCTION ABOUT',' ',regex=True)
    .str.replace(r'INTRODUCTION',' ',regex=True)
    .str.replace(r'\s+',' ',regex=True)
    .str.strip()
)

In [ ]:
final_df.loc[:, 'knowledge_text']=(

"Disease: "+final_df['disease_name']+

" | Medicine: "+final_df['med_name']+

" | Generic: "+final_df['generic_name']+

" | Manufacturer: "+final_df['drug_manufacturer']+

" | Prescription: "+final_df['prescription_required']+

" | Price: "+final_df['final_price_clean'].astype(str)+

" | Description: "+final_df['drug_content']

)

In [ ]:
final_df['knowledge_text'][0]

"Disease: ADHD | Medicine: Atrest 25mg Tablet 10'S | Generic: Tetrabenazine 25 mg | Manufacturer: Centaur Pharmaceuticals Pvt Ltd | Prescription: Rx required | Price: 335.68 | Description: ATREST 25MG TABLETATREST 25MG TABLET contains Tetrabenazine which belongs to the group of medicines called Vesicular monoamine transporter 2 inhibitors. ATREST 25MG TABLET is used to manage diseases that cause hyperkinetic motor disorders (such as jerky, irregular, uncontrollable movements) associated with Huntington's chorea (an inherited neurodegenerative disease) in affected individuals. ATREST 25MG TABLET is not recommended for use in patients allergic to Tetrabenazine. It is also not recommended for use in patients suffering from Parkinson-like symptoms, depression, active suicidal thoughts, pheochromocytoma (tumor of the adrenal gland), and/or kidney disorders. Before taking ATREST 25MG TABLET, inform your doctor if you are intolerant to certain sugars (such as lactose), and/or have heart problems (such as long QT syndrome, heart rhythm disorders), liver problems (such as mild, moderate/severe hepatic disorders). ATREST 25MG TABLET should be used with caution during pregnancy and in women planning for pregnancy only if it is clearly necessary. It is not recommended for use in breastfeeding women. The medicine is not recommended for use in children and adolescents (aged below 18 years) and is advised to be used with caution in elderly patients (aged 65 years/above) after consulting the doctor. The most common side effects of taking ATREST 25MG TABLET are confusion, anxiety, sleeplessness, low blood pressure, nausea, vomiting, diarrhea, and/or constipation. Consult your doctor if any these symptoms worsen. USES OF ATREST 25MG TABLET Manage diseases that cause hyperkinetic motor disorders (such as jerky, irregular, uncontrollable movements) associated with Huntington's chorea (an inherited neurodegenerative disease) in affected individuals HOW ATREST 25MG TABLET WORKSATREST 25MG TABLET works by inhibiting the absorption of certain chemicals (dopamine, serotonin) in brain which results in improved movements thus managing hyperkinetic motor disorders associated with Huntington's chorea in affected individuals. DIRECTIONS FOR USETake ATREST 25MG TABLET as advised by your physician. Swallow the medicine with water. Do not crush or chew the medicine. Your doctor will decide the correct dose and duration for you depending upon your age, body weight and disease condition. SIDE EFFECTS OF ATREST 25MG TABLETCOMMON drowsiness (with higher dosages) Parkinson-like symptoms (such as uncontrollable movements of the head, legs, hands, arms) confusion, anxiety sleeplessness low blood pressure dysphagia (difficulty in swallowing) nausea, vomiting, diarrhea, constipation sweating UNCOMMON mental changes (such as confusion, hallucinations) stiffness in your muscles fever RARE signs of Neuroleptic malignant syndrome (life threatening reaction to antipsychotic drug) such as mental changes (confusion, hallucinations), stiffness in muscles, and/or temperature Stop taking ATREST 25MG TABLET and contact your doctor immediately if you experience any of the following side effects: feeling sad/depressed suicidal thoughts have/plan to hurt yourself intentionally HOW TO MANAGE SIDE EFFECTSNausea and vomiting: Take ATREST 25MG TABLET with/just after a meal. Stick to simple meals. Avoid eating oil rich/spicy foods, sugary snacks and drinks. Avoid drinking too much liquid along with your meals, and drink slowly in between meals. Consult your doctor if the condition worsens. Diarrhoea: Drink plenty of water and stay hydrated. Try to avoid taking any medicine on your own to manage diarrhea. Consult and inform your doctor if the symptom worsens. Constipation: Try to eat high-fiber foods such as vegetables, cereals, fresh fruit, and drink plenty of water. Involve in regular exercise (going for a daily walk or run) and if this does not help, consult and inform your doctor for receiving alternate managements for constipation. WARNING & PRECAUTIONSPREGNANCYATREST 25MG TABLET should be used with caution during pregnancy and in women planning for pregnancy only if it is clearly necessary. Consult your doctor before taking the medicine. BREASTFEEDINGATREST 25MG TABLET is not recommended for use in breastfeeding women. Consult your doctor before taking the medicine. DRIVING AND USING MACHINESDo not drive/operate machines if you feel drowsy after taking ATREST 25MG TABLET. ALCOHOLAvoid consumption of alcohol while taking ATREST 25MG TABLET since the medicine may make you feel abnormally sleepy. KIDNEYATREST 25MG TABLET is not recommended for use in patients with kidney disorders. Consult your doctor before taking ATREST 25MG TABLET. LIVERATREST 25MG TABLET should be used with caution in patients with liver problems such as mild, moderate, and/or severe hepatic disorders. Consult your doctor before taking ATREST 25MG TABLET. ALLERGYDo not take ATREST 25MG TABLET if you are allergic to Tetrabenazine, and/or any other ingredients of this medicine. HEART DISEASEATREST 25MG TABLET should be used with caution in patients with heart problems such as long QT syndrome, and/or problems associated with heart rhythm. Consult your doctor before taking ATREST 25MG TABLET. OTHERSATREST 25MG TABLET is not recommended for use if you: suffer from Parkinson-like symptoms are diagnosed with depression which has not been managed or difficult to manage have active suicidal thoughts have pheochromocytoma (tumor of the adrenal gland) have prolactin-dependent tumors such as pituitary/ breast cancer Before taking ATREST 25MG TABLET, inform your doctor if you: are a slow/intermediate metabolizer of an enzyme called CYP2D6 (enzyme responsible for metabolism of medicines) are intolerant to certain sugars such as lactose Use in Pediatrics: ATREST 25MG TABLET is not recommended for use in children and adolescents (aged below 18 years). Consult your doctor before taking ATREST 25MG TABLET. Use in Geriatrics: ATREST 25MG TABLET should be used with caution in elderly patients (aged 65 years/above). Consult your doctor before taking ATREST 25MG TABLET. INTERACTIONSA. Drug-Drug interactions: Before taking ATREST 25MG TABLET, inform your doctor if you are taking any of the following medicine: reserpine (used to control high blood pressure and manage psychosis) antidepressants (used to manage depression) such as MAO inhibitors (Ex. phenelzine, selegiline) levodopa (used to manage Parkinson’s disease) opioids (used to control pain) Ex. oxycodone, hydrocodone antihypertensive drugs (used to manage high blood pressure) Ex. telmisartan, chlorthalidone beta blockers (used to manage heart problems) Ex. acebutolol, atenolol medicines used to manage psychotic disorders such as hypnotics (Ex. ambien, belsomra), neuroleptics (Ex. butaperazine) CYP2D6 inhibitors (medicines used to reduce the metabolism of certain medicines) Ex. fluoxetine, paroxetine, terbinafine, moclobemide, quinidine medicines that prolong the QTc interval in the ECG (Ex. haloperidol, droperidol) certain antibiotics (used to manage bacterial infections) Ex. gatifloxacin, moxifloxacin medicines used to manage heart rhythm conditions (Ex. quinidine, procainamide, amiodarone, sotalol) Overdosage: If you or anyone else accidentally take too much of ATREST 25MG TABLET, consult your doctor immediately or visit the nearby hospital. Symptoms of overdose are uncontrollable muscle spasms (affecting eyes, head, neck and body), uncontrolled rolling of eyes, excessive blinking of eye, nausea, vomiting, diarrhea, sweating, dizziness, feeling cold, confusion, hallucinations, drowsiness, redness/inflammation, and/or tremor. SYNOPSIS Drug : Tetrabenazine Pharmacological Category : Vesicular monoamine transporter 2 inhibitor Therapeutic Indication : Hyperkinetic motor disorders associated with Huntington's chorea Dosage Forms : Tablet MORE INFORMATION Keep ATREST 25MG TABLET out of reach of children Store ATREST 25MG TABLET at room temperature FAQs ABOUT ATREST 25MG TABLETWhat is ATREST 25MG TABLET used for? ATREST 25MG TABLET is used to manage diseases that cause hyperkinetic motor disorders (such as jerky, irregular, uncontrollable movements) associated with Huntington's chorea (an inherited neurodegenerative disease) in affected individuals. What are the common side effects of taking ATREST 25MG TABLET? The most common side effects of taking ATREST 25MG TABLET are confusion, anxiety, sleeplessness, low blood pressure, nausea, vomiting, diarrhea, and/or constipation. Consult your doctor if any these symptoms worsen. How ATREST 25MG TABLET works? ATREST 25MG TABLET works by inhibiting the absorption of certain chemicals (dopamine, serotonin) in brain which results in improved movements thus managing hyperkinetic motor disorders associated with Huntington's chorea in affected individuals. How ATREST 25MG TABLET should be taken? Take ATREST 25MG TABLET as advised by your physician. Swallow the medicines with a glass of water. Do not crush or chew the medicine. Your physician will decide the correct dose and duration for you depending upon your age, body weight and disease condition. Can ATREST 25MG TABLET be used in pregnant and breastfeeding women? Yes, ATREST 25MG TABLET can be used but with caution during pregnancy and in women planning for pregnancy only if it is clearly necessary. The medicine is not recommended for use in breastfeeding women. Consult your doctor before taking the medicine. REFERENCES1. Goodman Gilmans. Treatment of central nervous system degenerative disorders. The Pharmacological Basis of Therapeutics. Twelfth Edition. 2011. Page : 436, 624. 2. Tatiana Yero, Jose A. Rey. Tetrabenazine (Xenazine), An FDA-Approved Treatment Option for Huntington’s Disease–Related Chorea. NIH National Library of Medicine. National Center for Biotechnology Information. PMC PubMed Central. December 2008. [Accessed on 1st June 2022] https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2730806/ 3. Joseph M. Ferrara, Giovanni Mostile, Christine Hunter, Octavian R. Adam, Joseph Jankovic. Effect of Tetrabenazine on Motor Function in Patients with Huntington Disease. NIH National Library of Medicine. National Center for Biotechnology Information. PMC PubMed Central. December 2012. [Accessed on 1st June 2022] https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4389035/ 4. Sun Pharmaceutical Industries Europe B.V. Electronic Medicines Compendium (EMC). [Revised in August 2021] [Accessed on 1st June 2022] https://www.medicines.org.uk/emc/files/pil.2668.pdf 5. Sun Pharmaceutical Industries Europe B.V. Electronic Medicines Compendium (EMC). [Revised in August 2021] [Accessed on 1st June 2022] https://www.medicines.org.uk/emc/product/2668/smpc AUTHOR DETAILS Written By Dr. K .AZEEM HUSSAIN - B.D.S Reviewed By Dr. Sankara Babu Gorle - MBBS, MD(Pharmacology) View profile Last updated on 20 Dec 2022 | 05:49 PM(IST)"

In [ ]:
final_df.to_csv(
    "chatbot_ready_medicine_data.csv",
    index=False
)

print("saved successfully")

saved successfully

**Embedding **

In [ ]:
!pip install sentence-transformers faiss-cpu -q

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 23.8/23.8 MB 68.6 MB/s eta 0:00:00

In [ ]:
from sentence_transformers import SentenceTransformer
import numpy as np

In [ ]:
model = SentenceTransformer(
    'all-MiniLM-L6-v2'
)

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:93: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md: 0.00B [00:00, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/90.9M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

In [ ]:
texts = final_df['knowledge_text'].tolist()

embeddings = model.encode(
    texts,
    show_progress_bar=True
)

print(embeddings.shape)

Batches:   0%|          | 0/749 [00:00<?, ?it/s]

(23939, 384)

**Building vector DB**

In [ ]:
import faiss

In [ ]:
dimension = embeddings.shape[1]

index = faiss.IndexFlatL2(dimension)

index.add(
    np.array(embeddings).astype('float32')
)

print("Total vectors:", index.ntotal)

Total vectors: 23939

In [ ]:
def search_medicine(query, k=5):

    query_embedding = model.encode([query])

    distances, indices = index.search(
        np.array(query_embedding).astype('float32'),
        k
    )

    return final_df.iloc[
        indices[0]
    ][[
        'disease_name',
        'med_name',
        'generic_name',
        'final_price_clean'
    ]]

In [ ]:
search_medicine(
    "I have diabetes"
)

,disease_name,med_name,generic_name,final_price_clean
8015,Diabetes,GLIBETAG 2.5mg Tablet 10's,Glibenclamide 2.5 mg Also Known As: Glyburide,6.64
7985,Diabetes,GLZ Total Tablet 10'S,Gliclazide 60 mg+Metformin 500 mg+Pioglitazone...,119.10
7297,Diabetes,COSPIAQ 10mg Tablet 10's,Empagliflozin 10 mg,528.30
7342,Diabetes,Daonil 5mg Tablet 30'S,Glibenclamide 5 mg Also Known As: Glyburide,48.26
7522,Diabetes,DAPABLIS 10 Tablet 10's,Dapagliflozin 10 mg,132.88

In [ ]:
search_medicine(
    "I have bacterial infection"
)

,disease_name,med_name,generic_name,final_price_clean
3037,Bacterial Infections,BACTORUS 1.5 Injection 1's,Cefoperazone 1000 mg+Sulbactam 500 mg,193.60
8319,Diarrhoea,Sporlac Tablet 20'S,LACTOBACILLUS SPOROGENES +BACILLUS CLAUSII +BA...,233.46
3171,Bacterial Infections,CEFRINE Capsule 10's,Cefdinir 300 mg,322.96
3778,Bacterial Infections,DINIBACT 300mg Tablet 6's,Cefdinir 300 mg,274.14
3291,Bacterial Infections,Clavam Dry Syrup 30ml,Amoxycillin 125 mg+Clavulanic Acid 31.25 mg,61.99